packages:
  - "apps/*"
  - "packages/*"
  - "modules/*"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260810.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260810.1'
  - '@cloudflare/workerd-linux-64@1.20260810.1'
  - '@cloudflare/workerd-linux-arm64@1.20260810.1'
  - '@cloudflare/workerd-windows-64@1.20260810.1'
  - workerd@1.20260810.1

overrides:
  sharp: 0.35.4
  workerd: 1.20260810.1
