/**
 * AUTO-GENERATED by db/generate-schema-docs.ts — do not edit by hand.
 * Regenerate after any migration:  npm run docs:schema
 */
export type SchemaColumn = {
  name: string
  type: string
  nullable: boolean
  def: string | null
}
export type SchemaTable = {
  name: string
  module: string
  columns: SchemaColumn[]
}

export const SCHEMA_TABLES: SchemaTable[] = [
  {
    "name": "account",
    "module": "Auth (Better Auth)",
    "columns": [
      {
        "name": "id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "account_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "provider_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "user_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "access_token",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "refresh_token",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "id_token",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "access_token_expires_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "refresh_token_expires_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "scope",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "password",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "invitation",
    "module": "Auth (Better Auth)",
    "columns": [
      {
        "name": "id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "organization_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "email",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "role",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "text",
        "nullable": false,
        "def": "'pending'"
      },
      {
        "name": "expires_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": null
      },
      {
        "name": "inviter_id",
        "type": "text",
        "nullable": false,
        "def": null
      }
    ]
  },
  {
    "name": "member",
    "module": "Auth (Better Auth)",
    "columns": [
      {
        "name": "id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "organization_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "user_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "role",
        "type": "text",
        "nullable": false,
        "def": "'member'"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "organization",
    "module": "Auth (Better Auth)",
    "columns": [
      {
        "name": "id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "slug",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "logo",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "metadata",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "session",
    "module": "Auth (Better Auth)",
    "columns": [
      {
        "name": "id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "expires_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": null
      },
      {
        "name": "token",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "ip_address",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "user_agent",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "user_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "active_organization_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "user",
    "module": "Auth (Better Auth)",
    "columns": [
      {
        "name": "id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "email",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "email_verified",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "image",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "is_superadmin",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "last_login_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "verification",
    "module": "Auth (Better Auth)",
    "columns": [
      {
        "name": "id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "identifier",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "value",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "expires_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "accounts",
    "module": "CRM",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "parent_account_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "account_type",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "industry",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "website",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "billing_address",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "owner_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "custom_fields",
        "type": "jsonb",
        "nullable": false,
        "def": "'{}'"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "deleted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "registration_number",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "code",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "end_user_account_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "phone",
        "type": "text",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "leads",
    "module": "CRM",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "company_name",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "email",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "phone",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "source",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "lead_status (new | contacted | qualified | disqualified | converted)",
        "nullable": false,
        "def": "'new'"
      },
      {
        "name": "disqualify_reason",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "owner_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "converted_account_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "converted_person_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "converted_opportunity_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "converted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "deleted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "pipeline_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "current_stage_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "persons",
    "module": "CRM",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "account_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "first_name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "last_name",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "title",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "email",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "phone",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "is_primary",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "custom_fields",
        "type": "jsonb",
        "nullable": false,
        "def": "'{}'"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "deleted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "finance_docs",
    "module": "Finance add-on",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "kind",
        "type": "finance_doc_kind (delivery_order | invoice | credit_note | receipt | rfq | purchase_order | purchase_invoice | payment)",
        "nullable": false,
        "def": null
      },
      {
        "name": "number",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "parent_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "sales_order_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "project_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "milestone_id",
        "type": "uuid (deprecated historical invoice link; no live linkage)",
        "nullable": true,
        "def": null
      },
      {
        "name": "party_name",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "amount",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "status",
        "type": "finance_doc_status (draft | issued | settled | cancelled)",
        "nullable": false,
        "def": "'draft'"
      },
      {
        "name": "doc_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "due_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "notes",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "reminder_stage",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "last_reminder_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "intercompany_deal_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "counterpart_doc_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "counterpart_number",
        "type": "text",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "intercompany_deal_parties",
    "module": "Intercompany",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "partner_entity_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "share_type",
        "type": "intercompany_share_type (percent | amount)",
        "nullable": false,
        "def": "'amount'"
      },
      {
        "name": "share_value",
        "type": "numeric",
        "nullable": false,
        "def": null
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "manual_fx_rate",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "sort_order",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "intercompany_deal_responses",
    "module": "Intercompany",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "deal_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "origin_tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "response",
        "type": "intercompany_response (accepted | declined)",
        "nullable": false,
        "def": null
      },
      {
        "name": "reason",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "responded_by_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "responded_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "intercompany_deals",
    "module": "Intercompany",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "partner_tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "account_name",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "estimated_amount",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "quoted_amount",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "text",
        "nullable": false,
        "def": "'open'"
      },
      {
        "name": "stage_name",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "expected_close_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "project_year",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "stage_probability",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "include_in_forecast",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "share_type",
        "type": "intercompany_share_type (percent | amount)",
        "nullable": false,
        "def": "'amount'"
      },
      {
        "name": "share_value",
        "type": "numeric",
        "nullable": false,
        "def": null
      },
      {
        "name": "partner_currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "manual_fx_rate",
        "type": "numeric",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "activities",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "entity_type",
        "type": "activity_entity_type (account | person | lead | opportunity | project | finance_doc)",
        "nullable": false,
        "def": null
      },
      {
        "name": "entity_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "type",
        "type": "activity_type (note | call | meeting | email | system | stage_change | file)",
        "nullable": false,
        "def": "'note'"
      },
      {
        "name": "subject",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "body",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "occurred_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "outcome",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "next_step",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "due_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "attachments",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "attachable_type",
        "type": "attachable_type (stage_approval_request | quotation | opportunity | account | lead | person | project | sales_order | finance_doc)",
        "nullable": false,
        "def": null
      },
      {
        "name": "attachable_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "file_name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "content_type",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "byte_size",
        "type": "bigint",
        "nullable": false,
        "def": null
      },
      {
        "name": "storage_key",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "checksum",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "uploaded_by_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "audit_log",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "actor_user_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "actor_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "action",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "entity_type",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "entity_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "before",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "after",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "ip",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "custom_field_defs",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "entity_type",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "field_key",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "label",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "data_type",
        "type": "custom_field_type (text | number | date | boolean | select)",
        "nullable": false,
        "def": "'text'"
      },
      {
        "name": "options",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "is_required",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "sort_order",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "membership_profiles",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "member_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "role_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "tier_level",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "manager_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "member_status (active | invited | disabled)",
        "nullable": false,
        "def": "'active'"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "pending_invites",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "email",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "role_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "tier_level",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "invited_by_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "permissions",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "key",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "description",
        "type": "text",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "project_counters",
    "module": "Platform",
    "columns": [
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "year",
        "type": "integer",
        "nullable": false,
        "def": null
      },
      {
        "name": "next_number",
        "type": "integer",
        "nullable": false,
        "def": "1"
      }
    ]
  },
  {
    "name": "role_permissions",
    "module": "Platform",
    "columns": [
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "role_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "permission_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      }
    ]
  },
  {
    "name": "roles",
    "module": "Platform",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "description",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "is_system",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "default_tier_level",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "tenant_settings",
    "module": "Platform",
    "columns": [
      {
        "name": "organization_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "default_currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "status",
        "type": "org_status (active | suspended)",
        "nullable": false,
        "def": "'active'"
      },
      {
        "name": "fiscal_year_start_month",
        "type": "integer",
        "nullable": false,
        "def": "1"
      },
      {
        "name": "approval_bypass_tier",
        "type": "integer",
        "nullable": false,
        "def": "40"
      },
      {
        "name": "tax_inclusive",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "auto_win_on_quote_accept",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "allow_password_login",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "industries",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "quote_prefix",
        "type": "text",
        "nullable": false,
        "def": "'Q-'"
      },
      {
        "name": "quote_next_number",
        "type": "integer",
        "nullable": false,
        "def": "1"
      },
      {
        "name": "quote_pad_width",
        "type": "integer",
        "nullable": false,
        "def": "4"
      },
      {
        "name": "entity_code",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "project_next_number",
        "type": "integer",
        "nullable": false,
        "def": "1"
      },
      {
        "name": "project_pad_width",
        "type": "integer",
        "nullable": false,
        "def": "3"
      },
      {
        "name": "so_next_number",
        "type": "integer",
        "nullable": false,
        "def": "1"
      },
      {
        "name": "so_pad_width",
        "type": "integer",
        "nullable": false,
        "def": "4"
      },
      {
        "name": "product_types",
        "type": "jsonb",
        "nullable": false,
        "def": "'[]'"
      },
      {
        "name": "product_codes",
        "type": "jsonb",
        "nullable": false,
        "def": "'[]'"
      },
      {
        "name": "custom_funnel_fields",
        "type": "jsonb",
        "nullable": false,
        "def": "'[]'"
      },
      {
        "name": "auto_join_domains",
        "type": "jsonb",
        "nullable": false,
        "def": "'[]'"
      },
      {
        "name": "auto_join_role",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "countries",
        "type": "jsonb",
        "nullable": false,
        "def": "'[]'"
      },
      {
        "name": "intercompany_partner_ids",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "currencies",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "payment_terms",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "quote_valid_days",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "lead_sources",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "loss_reasons",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "so_document_kinds",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "company_address",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "company_registration_no",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "company_phone",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "company_email",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "company_website",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "bank_details",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "quote_footer",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "logo_storage_key",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "logo_content_type",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "follow_up_due_days",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "auto_create_project_on_accept",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "milestone_template",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "default_country",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "phone_prefix",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "stale_deal_days",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "lead_follow_up_days",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "finance_module",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "invoice_reminder_days",
        "type": "jsonb",
        "nullable": true,
        "def": null
      },
      {
        "name": "invoice_due_days",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "interco_auto_mirror",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "documentation_module",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      }
    ]
  },
  {
    "name": "contract_years",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "year",
        "type": "integer",
        "nullable": false,
        "def": null
      },
      {
        "name": "title",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "amount",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "status",
        "type": "text",
        "nullable": false,
        "def": "'planned'"
      },
      {
        "name": "notes",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "sort_order",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "deal_costs",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "category",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "contract_year",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "party_kind",
        "type": "text",
        "nullable": false,
        "def": "'supplier'"
      },
      {
        "name": "supplier_name",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "po_number",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "amount",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "exchange_rate",
        "type": "numeric",
        "nullable": false,
        "def": "'1'"
      },
      {
        "name": "amount_base",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "notes",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "pipeline_stages",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "pipeline_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "code",
        "type": "stage_code (0e | 1d | 2c | 3b | 4a | won | lost | kiv)",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "probability",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "kind",
        "type": "stage_kind (OPEN | WON | LOST | PARKED)",
        "nullable": false,
        "def": null
      },
      {
        "name": "sort_order",
        "type": "integer",
        "nullable": false,
        "def": null
      },
      {
        "name": "requires_approval_to_enter",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "include_in_forecast",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "required_fields",
        "type": "jsonb",
        "nullable": false,
        "def": "'[]'"
      }
    ]
  },
  {
    "name": "pipelines",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "is_default",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "is_active",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "funnels",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "account_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "primary_person_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "pipeline_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "current_stage_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "owner_member_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "primary_quotation_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "amount",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "expected_close_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "actual_close_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "opportunity_status (open | won | lost | on_hold)",
        "nullable": false,
        "def": "'open'"
      },
      {
        "name": "kiv_review_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "lost_reason",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "closed_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "custom_fields",
        "type": "jsonb",
        "nullable": false,
        "def": "'{}'"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "deleted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "product_type_code",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "estimated_amount",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "recognized_percent",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "description",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "project_year",
        "type": "integer",
        "nullable": true,
        "def": null
      },
      {
        "name": "is_intercompany",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "project_natures",
        "type": "jsonb",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "funnel_stage_history",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "from_stage_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "to_stage_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "changed_by_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "approval_request_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "probability_at_change",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "value_at_change",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "source",
        "type": "stage_change_source (manual | approval | quote_accept | reopen)",
        "nullable": false,
        "def": "'manual'"
      },
      {
        "name": "changed_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "reason",
        "type": "text",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "payment_milestones",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "project_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "quotation_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "title",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "description",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "amount",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "due_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "payment_milestone_status (pending_invoicing | invoiced)",
        "nullable": false,
        "def": "'pending_invoicing'"
      },
      {
        "name": "sort_order",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "split_percentage",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "invoice_number",
        "type": "text (deprecated historical snapshot; no live linkage)",
        "nullable": true,
        "def": null
      },
      {
        "name": "invoice_date",
        "type": "date (deprecated historical snapshot; no live linkage)",
        "nullable": true,
        "def": null
      },
      {
        "name": "expected_invoice_month",
        "type": "text (deprecated historical planning field)",
        "nullable": true,
        "def": null
      },
      {
        "name": "expected_invoice_year",
        "type": "integer (deprecated historical planning field)",
        "nullable": true,
        "def": null
      },
      {
        "name": "so_number",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "product_category",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "product_subcategory",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "is_default",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "products",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "product_code",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "subcategory",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "uom",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "standard_price",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "description",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "is_active",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "deleted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "projects",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "project_code",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "account_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "quotation_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "owner_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "project_status (planning | active | on_hold | completed | cancelled)",
        "nullable": false,
        "def": "'planning'"
      },
      {
        "name": "start_date",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "value",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "notes",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "deleted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "code_nature",
        "type": "text",
        "nullable": false,
        "def": "'auto'"
      },
      {
        "name": "product_type_code",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "intercompany_deal_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "quotation_line_items",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "quotation_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "description",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "quantity",
        "type": "numeric",
        "nullable": false,
        "def": "'1'"
      },
      {
        "name": "unit_price",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "discount_percent",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "tax_setting_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "line_subtotal",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "line_tax",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "line_total",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "sort_order",
        "type": "integer",
        "nullable": false,
        "def": "0"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "product_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "uom",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "project_nature_code",
        "type": "text",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "quotations",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "quote_number",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "version",
        "type": "integer",
        "nullable": false,
        "def": "1"
      },
      {
        "name": "is_primary",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "status",
        "type": "quotation_status (draft | sent | accepted | rejected | expired | void)",
        "nullable": false,
        "def": "'draft'"
      },
      {
        "name": "currency",
        "type": "character",
        "nullable": false,
        "def": "'MYR'"
      },
      {
        "name": "tax_setting_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "tax_rate_snapshot",
        "type": "numeric",
        "nullable": true,
        "def": null
      },
      {
        "name": "subtotal",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "discount_total",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "tax_total",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "total",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "valid_until",
        "type": "date",
        "nullable": true,
        "def": null
      },
      {
        "name": "notes",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "sent_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "accepted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "deleted_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "header_discount",
        "type": "numeric",
        "nullable": false,
        "def": "'0'"
      },
      {
        "name": "tax_inclusive",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "product_type_code",
        "type": "text",
        "nullable": true,
        "def": null
      }
    ]
  },
  {
    "name": "sales_orders",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "project_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "so_number",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "document_kind",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "payment_term",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "status",
        "type": "sales_order_status (submitted | approved | rejected)",
        "nullable": false,
        "def": "'submitted'"
      },
      {
        "name": "submitted_by_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "reviewed_by_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "reject_reason",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "notes",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "submitted_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "reviewed_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "stage_approval_requests",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "funnel_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "requester_member_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "from_stage_id",
        "type": "uuid",
        "nullable": true,
        "def": null
      },
      {
        "name": "target_stage_id",
        "type": "uuid",
        "nullable": false,
        "def": null
      },
      {
        "name": "reason",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "status",
        "type": "approval_status (pending | approved | rejected | cancelled)",
        "nullable": false,
        "def": "'pending'"
      },
      {
        "name": "approver_member_id",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "decision_note",
        "type": "text",
        "nullable": true,
        "def": null
      },
      {
        "name": "requested_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "decided_at",
        "type": "timestamp with time zone",
        "nullable": true,
        "def": null
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  },
  {
    "name": "tax_settings",
    "module": "Sales",
    "columns": [
      {
        "name": "id",
        "type": "uuid",
        "nullable": false,
        "def": "gen_random_uuid()"
      },
      {
        "name": "tenant_id",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "name",
        "type": "text",
        "nullable": false,
        "def": null
      },
      {
        "name": "rate_percent",
        "type": "numeric",
        "nullable": false,
        "def": null
      },
      {
        "name": "is_default",
        "type": "boolean",
        "nullable": false,
        "def": "false"
      },
      {
        "name": "is_active",
        "type": "boolean",
        "nullable": false,
        "def": "true"
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      },
      {
        "name": "updated_at",
        "type": "timestamp with time zone",
        "nullable": false,
        "def": "now()"
      }
    ]
  }
]
